[1,"\u001B[0m\u001B[1m\u001B[31merror\u001B[0m: Uncaught (in promise) Error: Project _quarto.yml validation failed.\n\nIn file _quarto.yml\n(line 46, columns 9--17) Key \u001B[34mcontents\u001B[39m has empty value but it must instead be an array of values, where each element must be at least one of: navigation-item, a string, an object\n45: \u001B[34m      - section: \"**Lecture Materials**\"\u001B[39m\n46: \u001B[34m        contents:\u001B[39m\n                     \n47: \u001B[34m      - section: \"**Final Project**\"\u001B[39m\n\n\nIn file _quarto.yml\n(line 48, columns 9--17) Key \u001B[34mcontents\u001B[39m has empty value but it must instead be an array of values, where each element must be at least one of: navigation-item, a string, an object\n47: \u001B[34m      - section: \"**Final Project**\"\u001B[39m\n48: \u001B[34m        contents: \u001B[39m\n                     \n\n        throw new ValidationError2(errorMessage, yamlValidationErrors);\n\u001B[0m\u001B[31m              ^\u001B[0m\n    at \u001B[0m\u001B[1m\u001B[3mreadAndValidateYamlFromFile\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m19068\u001B[0m:\u001B[0m\u001B[33m15\u001B[0m)\n    at async \u001B[0m\u001B[1m\u001B[3mprojectContext\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m42833\u001B[0m:\u001B[0m\u001B[33m33\u001B[0m)\n    at async \u001B[0m\u001B[1m\u001B[3mrender\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m76757\u001B[0m:\u001B[0m\u001B[33m21\u001B[0m)\n"]
